# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: twikoo
spec:
  enabled: true
  requires: ">=2.11.0"
  author:
    name: Chenhe
    website: https://chenhe.me
  logo: logo.png
  settingName: twikoo-settings
  configMapName: twikoo-configMap
  homepage: https://github.com/ichenhe/halo-twikoo#readme
  repo: https://github.com/ichenhe/halo-twikoo
  issues: https://github.com/ichenhe/halo-twikoo/issues
  displayName: "Twikoo"
  description: "集成 Twikoo 评论系统到 Halo"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/ichenhe/halo-twikoo/blob/main/LICENSE"
